name: piblish

on:
  push:
    tags:
      - '*'

jobs:

  publish-gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            VERSION=${{ steps.get_tag.outputs.TAG }}
            GIT_COMMIT=${{ github.sha }}
            GIT_COMMIT_MESSAGE=${{ github.event.head_commit.message }}
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/gateway:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/gateway:${{ github.sha }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/gateway:latest
  publish-auth-plugins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
        svc: [
          basic-auth
        ]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::latest-dev
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./auth/${{ matrix.svc }}
          file: ./auth/${{ matrix.svc }}/Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ matrix.svc }}:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ matrix.svc }}:${{ github.sha }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ matrix.svc }}:latest
